import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white flex flex-col min-h-screen`}
      >
        {/* Page content */}
        <div className="flex-grow">{children}</div>

        {/* Global footer */}
        <footer className="w-full text-center text-sm text-gray-400 py-2 border-t border-yellow-500 bg-black">
          <p>© {new Date().getFullYear()} WRAKcoin. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
